[build]
  command = "npm install && cd functions && npm install"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
